name: mario
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1g=h1de35cc_0
  - pip=20.0.2=py38_3
  - python=3.8.3=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=46.4.0=py38_0
  - sqlite=3.31.1=h5c1f38d_1
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cloudpickle==2.0.0
    - future==0.18.2
    - gym==0.21.0
    - gym-super-mario-bros==7.3.2
    - nes-py==8.1.8
    - numpy==1.21.2
    - matplotlib==3.4.3
    - opencv-python==4.5.3.56
    - pillow==8.3.2
    - pyglet==1.5.21
    - scikit-image==0.18.3
    - scipy==1.7.1
    - torch==1.9.1
    - torchvision==0.10.1
    - tqdm==4.62.3
prefix: /opt/anaconda3/envs/mario
